<!DOCTYPE html>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="../js/jquery-1.3.2.min.js"></script>
        
        <style>
        table, th, td {
            /*border: 1px solid black;*/
            border-collapse: collapse;
        }
        th, td {
            /*padding-bottom: 5px;*/
            padding-top: 5px;
            padding-left: 140px;
        }
        </style>

    </head>
    <body>
        <div class="container">
            
            <section id="seccion">
                <form id="form1" method="post">
        
        <?php foreach($ciudades as $ciudad): 
            if ($ciudad->getId() == $id_ciudad_asociada){ 
                $ciudad_fotog = $ciudad->getNombre(); 
                }  
                endforeach; ?>
        
          <br>
           <?php foreach($provincias as $provincia): 
            if ($provincia->getId() == $id_provincia_asociada){ 
                $provincia_fotog = $provincia->getNombre(); 
                }  
                endforeach; ?>
        
          <br>
        <?php foreach($paises as $pais): 
            if ($pais->getId() == $id_pais_asociado){ 
                $pais_fotog = $pais->getNombre(); 
                }  
                endforeach; ?>
        
        <table style="width:50%" >
            <tr>
                <td><h1><?php echo $fotografo->getEmpresa(); ?></h1></td>
              </tr>
              <tr>
                <td><?php echo '  '; ?></td>
              </tr>
              <tr>
                <td><?php echo $fotografo->getNombre().' '; ?><?php echo $fotografo->getApellido(); ?></td>
              </tr>
              <tr>
                <td><?php echo $fotografo->getDireccion(); ?></td>
              </tr>
              <tr>
                <td><?php echo $ciudad_fotog; ?></td>
              </tr>
              <tr>
                <td><?php echo $provincia_fotog; ?></td>
              </tr>
              <tr>
                <td><?php echo $pais_fotog; ?></td>
              </tr>
              <tr>
                <td><?php echo '  '; ?></td>
              </tr>
              <tr>
                <td><?php echo '  '; ?></td>
              </tr>
              <tr>
                <td><?php echo $fotografo->getEmail(); ?></td>
              </tr>
              <tr>
                <td><?php echo $fotografo->getTelefono(); ?></td>
              </tr>

        </table>
          <br>
                    <input type="submit" value="Modificar" name="editar">
                    </form>
        </section>

        </div> <!-- /container -->
    </body>
</html>
