<!DOCTYPE html>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="../js/jquery-1.3.2.min.js"></script>
        <script type="text/javascript">
        $(document).ready(function(){
                $("#pais").change(function(){dependencia_estado();});
                $("#estado").change(function(){dependencia_ciudad();});
                $("#estado").attr("disabled",true);
                $("#ciudad").attr("disabled",true);
        });

        function dependencia_estado()
        {
                var code = $("#pais").val();
                $.get("../scripts/dependencia-estado.php?", { code: code },
                        function(resultado)
                        {
                                if(!resultado)
                                {
                                        alert("Error");
                                }
                                else
                                {
                                        $("#estado").attr("disabled",false);
                                        document.getElementById("estado").options.length=1;
                                        $('#estado').append(resultado);			
                                }
                        }
                );
        }

        function dependencia_ciudad()
        {
                var code = $("#estado").val();
                $.get("../scripts/dependencia-ciudades.php?", { code: code }, function(resultado){
                        if(!resultado)
                        {
                                alert("Error");
                        }
                        else
                        {
                                $("#ciudad").attr("disabled",false);
                                document.getElementById("ciudad").options.length=1;
                                $('#ciudad').append(resultado);          
                        }

                });	
        }
        $("#form1").submit( function(eventObj) {
      $('select.ciudad option:selected').val(); 
      return true;
  });
        </script>
    </head>
    <body>
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Agregar fotógrafo';
                 $this->headTitle($title);
                 ?>
                <h1><?php echo $this->escapeHtml($title); ?></h1>
                
                <form id="form1" method="post">
                    <input type="hidden" name="something" id="something">
                    Nombre: <input type="text" name="nombre"><br>
                    Apellido: <input type="text" name="apellido"><br>
                    Empresa: <input type="text" name="empresa"><br>
                    Email: <input type="text" name="email"><br>
                    Contraseña: <input type="text" name="contrasenia"><br>
                    Email alternativo: <input type="text" name="emailAlternativo"><br>
                    Direccion: <input type="text" name="direccion"><br>
                    Telefono: <input type="text" name="telefono"><br>

                    Pais: <select name="pais" id="pais">
                            <option value="0">Selecciona Uno...</option>
                            <?php foreach($paises as $pais): ?>
                            <option value="<?php echo $pais->getId(); ?>"><?php echo $pais->getNombre(); ?></opcion>
                            <?php endforeach; ?>
                        </select>
                    <br>
                    Provincia: <select id="estado" name="estado">
                          <option value="0">Selecciona Uno...</option>
                      </select>
                        <br>

                    Ciudad: <select name="ciudad" id="ciudad">
                        <option value="0">Selecciona Uno...</option>
                        </select>
                    <br>

                    Plan: <select name="plan">
                        <?php foreach($planes as $plan): ?>
                        <option value="<?php echo $plan->getId(); ?>"><?php echo $plan->getNombre(); ?></opcion>
                            <?php endforeach; ?>
                        </select>
                    <br>
          
                    Activo: <input type="checkbox" name="activo" ><br> 
                    <br>
                    <input type="submit" value="Agregar" name="agregar">
                      <input type="submit" value="Cancelar" name="agregar">
                    </form>
             </section>

        </div> <!-- /container -->
    </body>
</html>
