<!DOCTYPE html>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="../js/jquery-1.3.2.min.js"></script>
        <script type="text/javascript">
        $(document).ready(function(){
                $("#pais").change(function(){dependencia_estado();});
                $("#estado").change(function(){dependencia_ciudad();});
//                $("#estado").attr("disabled",true);
//                $("#ciudad").attr("disabled",true);
        });

        function dependencia_estado()
        {
                var code = $("#pais").val();
                $.get("../scripts/dependencia-estado.php?", { code: code },
                        function(resultado)
                        {
                                if(!resultado)
                                {
                                        alert("Error");
                                }
                                else
                                {
                                        $("#estado").attr("disabled",false);
                                        document.getElementById("estado").options.length=1;
                                        $('#estado').append(resultado);			
                                }
                        }
                );
        }

        function dependencia_ciudad()
        {
                var code = $("#estado").val();
                $.get("../scripts/dependencia-ciudades.php?", { code: code }, function(resultado){
                        if(!resultado)
                        {
                                alert("Error");
                        }
                        else
                        {
                                $("#ciudad").attr("disabled",false);
                                document.getElementById("ciudad").options.length=1;
                                $('#ciudad').append(resultado);          
                        }

                });	
        }
        $("#form1").submit( function(eventObj) {
      $('select.ciudad option:selected').val(); 
      return true;
  });
        </script>
    </head>
    <body>
        
        <h1>Editar fotografo</h1>
        <form id="form1" method="post">
            Nombre: <input type="text" name="nombre" value="<?php echo $fotografo->getNombre(); ?>"><br>
            Apellido: <input type="text" name="apellido" value="<?php echo $fotografo->getApellido(); ?>"><br>
            Email: <input type="text" name="email" value="<?php echo $fotografo->getEmail(); ?>"><br>
            Contraseña: <input type="text" name="contrasenia" value="<?php echo $fotografo->getContrasenia(); ?>"><br>
            Email alternativo: <input type="text" name="emailAlternativo" value="<?php echo $fotografo->getEmailAlternativo(); ?>"><br>
            Direccion: <input type="text" name="direccion" value="<?php echo $fotografo->getDireccion(); ?>"><br>
            Telefono: <input type="text" name="telefono" value="<?php echo $fotografo->getTelefono(); ?>"><br>
              
          Pais:     <select name="pais" id="pais">
                        <?php foreach($paises as $pais): ?>
                            <?php if ($pais->getId() == $id_pais_asociado){ ?>
                                <option value="<?php echo $pais->getId(); ?>" selected><?php echo $pais->getNombre(); ?></opcion>
                            <?php } else { ?>
                                <option value="<?php echo $pais->getId(); ?>"><?php echo $pais->getNombre(); ?></opcion>
                            <?php } ?>
                        <?php endforeach; ?>
                    </select>
          <br>
          Provincia: <select id="estado" name="estado">
                <option value="0">Selecciona Uno...</option>
                    <?php foreach($provincias as $provincia): ?>
                        <?php if ($provincia->getId() == $id_provincia_asociada){ ?>
                            <option value="<?php echo $provincia->getId(); ?>" selected><?php echo $provincia->getNombre(); ?></opcion>
                        <?php } else { ?>
                            <option value="<?php echo $provincia->getId(); ?>"><?php echo $provincia->getNombre(); ?></opcion>
                        <?php } ?>
                    <?php endforeach; ?>
            </select>
              <br>
          
          Ciudad: <select name="ciudad" id="ciudad">
              <option value="0">Selecciona Uno...</option>
                <?php foreach($ciudades as $ciudad): ?>
                    <?php if ($ciudad->getId() == $id_ciudad_asociada){ ?>
                        <option value="<?php echo $ciudad->getId(); ?>" selected><?php echo $ciudad->getNombre(); ?></opcion>
                    <?php } else { ?>
                        <option value="<?php echo $ciudad->getId(); ?>"><?php echo $ciudad->getNombre(); ?></opcion>
                    <?php } ?>
                <?php endforeach; ?>
              </select>
          <br>
          
            Plan: <select name="plan">
                  <?php foreach($planes as $plan): ?>
                  <?php if ($plan->getId() == $id_plan_asociado){ ?>
                      <option value="<?php echo $plan->getId(); ?>" selected><?php echo $plan->getNombre(); ?></opcion>
                  <?php } else { ?>
                      <option value="<?php echo $plan->getId(); ?>"><?php echo $plan->getNombre(); ?></opcion>
                  <?php } ?>
                    <?php endforeach; ?>
              </select>
            <br>
          
          <input type="submit" value="Modificar" name="editar">
            <input type="submit" value="Cancelar" name="editar">
        </form>
    </body>
</html>
