<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>   
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Fotografos';
                 $this->headTitle($title);
                 ?>
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
                 
            <p>
                <a href="<?php echo $this->url('fotografo', array('action'=>'add'));?>">Agregar fotografo</a>
            </p>
                

                <?php if (isset($fotografos)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                    </tr>
                    </thead>
                <?php foreach($fotografos as $fotografo): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $fotografo->getNombre(); ?></td>
                        <td><?php echo $fotografo->getApellido(); ?></td>
                        <td><?php echo $fotografo->getEmail(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('fotografo', array('action'=>'edit', 'id' => $fotografo->getId()));?>">Edit</a> |
                            <a href="<?php echo $this->url('fotografo', array('action'=>'delete', 'id' => $fotografo->getId()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            </section>

        </div> <!-- /container -->
    </body>
</html>
