<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Agregar producto';
                 $this->headTitle($title);
                 ?>
                
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
                 <br>
        <form method="post">
            
            Nombre: <input type="text" name="nombre"><br>
            Descripcion: <input type="text" name="descripcion"><br>
            Pixel horizontal minimo: <input type="text" name="pixelhorizmin"><br>
            Pixel vertical minimo: <input type="text" name="pixelvertmin"><br>
            Mm horizontal: <input type="text" name="mmhorizontal"><br>
            Mm vertical: <input type="text" name="mmvertical"><br>
            Pixel horizontal recomendado: <input type="text" name="pixelhorizrec"><br>
            Pixel vertical recomendado: <input type="text" name="pixelvertrec"><br>
            Peso: <input type="text" name="peso"><br>
            Orden: <input type="text" name="orden"><br>
            Codigo: <input type="text" name="codigo"><br>
            Tipo papel: <select name="tipopapel">
                <?php foreach($tipospapeles as $tipopapel): ?>
                <option value="<?php echo $tipopapel->getId(); ?>"><?php echo $tipopapel->getNombre(); ?></opcion>
                  <?php endforeach; ?>
            </select><br>
            Disponible: <input type="checkbox" name="disponible" ><br>
            <input type="submit" value="Agregar" name="agregar">
            <input type="submit" value="Cancelar" name="agregar">
        </form>
        </section>

        </div> <!-- /container -->
    </body>
</html>
