<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Agregar forma pago';
                 $this->headTitle($title);
                 ?>
                
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
                 <br>
        <form method="post">
            
            Codigo: <input type="text" name="codigo"><br>
            Nombre: <input type="text" name="nombre"><br>
            Descripcion: <input type="text" name="descripcion"><br>
            Disponible: <input type="checkbox" name="disponible" ><br>
            <input type="submit" value="Agregar" name="agregar">
            <input type="submit" value="Cancelar" name="agregar">
        </form>
        </section>

        </div> <!-- /container -->
    </body>
</html>
