<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Editar forma pago';
                 $this->headTitle($title);
                 ?>
                
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
        <form method="post">
            
            Codigo: <input type="text" name="codigo" value="<?php echo $formapago->getCodigo(); ?>"><br>
            Nombre: <input type="text" name="nombre" value="<?php echo $formapago->getNombre(); ?>"><br>
            Descripcion: <input type="text" name="descripcion" value="<?php echo $formapago->getDescripcion(); ?>"><br>
            
            Disponible: <input type="checkbox" name="disponible" <?php if($formapago->getDisponible()){?> checked <?php } ?><br>
            <br><input type="submit" value="Modificar" name="editar">
            <input type="submit" value="Cancelar" name="editar">
        </form>
        </section>

        </div> <!-- /container -->
    </body>
</html>
