<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       
        <h1>Agregar plan</h1>
        <form method="post">
            Codigo: <input type="text" name="codigo"><br>
            Nombre: <input type="text" name="nombre"><br>
            Almacenamiento: <input type="text" name="almacenamBasico"><br>
            Tamaño archivo: <input type="text" name="tamanioArchivo"><br>
            Precio: <input type="text" name="precio"><br>
            Disponible: <input type="checkbox" name="disponible" ><br>
            <input type="submit" value="Agregar" name="agregar">
            <input type="submit" value="Cancelar" name="agregar">
        </form>
    </body>
</html>
