<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Agregar plan';
                 $this->headTitle($title);
                 ?>
                
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
                 <br>
                 
                <form method="post">
                    Codigo: <input type="text" name="codigo"><br>
                    Nombre: <input type="text" name="nombre"><br>
                    Almacenamiento: <input type="text" name="almacenamBasico"><br>
                    Tamaño archivo: <input type="text" name="tamanioArchivo"><br>
                    Precio: <input type="text" name="precio"><br>
                    Disponible: <input type="checkbox" name="disponible" ><br><br>
                    <input type="submit" value="Agregar" name="agregar">
                    <input type="submit" value="Cancelar" name="agregar">
                </form>
            </section>
        
        </div> <!-- /container -->
    </body>
</html>
