<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
         <h1>Agregar Almacenamiento Extra</h1>
         <form method="post">
            Almacenamiento: <input type="text" name="almacenamExtra"><br>
            Precio: <input type="text" name="precio"><br>
            Plan: <select name="plan">
                <?php foreach($planes as $plan): ?>
                <option value="<?php echo $plan->getId(); ?>"><?php echo $plan->getNombre(); ?></opcion>
                  <?php endforeach; ?>
            </select>
          <br>
          <input type="submit" value="Agregar" name="agregar">
            <input type="submit" value="Cancelar" name="agregar">
        </form>
        <?php
        
        ?>
    </body>
</html>
