<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
         <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Agregar almacenamiento extra';
                 $this->headTitle($title);
                 ?>
                
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
                 <br>
                 <form method="post">
                    Almacenamiento: <input type="text" name="almacenamExtra"><br>
                    Precio: <input type="text" name="precio"><br>
                    Plan: <select name="plan">
                        <?php foreach($planes as $plan): ?>
                        <option value="<?php echo $plan->getId(); ?>"><?php echo $plan->getNombre(); ?></opcion>
                          <?php endforeach; ?>
                    </select>
                  <br><br>
                  <input type="submit" value="Agregar" name="agregar">
                    <input type="submit" value="Cancelar" name="agregar">
                </form>
            </section>
        
        </div> <!-- /container -->
    </body>
</html>
