<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <h1>Eliminar plan</h1>
        Are you sure you want to delete plan <?php echo $plan->getCodigo(); ?>? <br/>
        <form method="post">
            <br> <br>
            <input type="submit" value="Eliminar" name="del">
            <input type="submit" value="Cancelar" name="del">
        </form>
    </body>
</html>
