<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
         <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Editar descuento';
                 $this->headTitle($title);
                 ?>
                
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
         <form method="post">
            Meses pagados: <input type="text" name="meses" value="<?php echo $descuento->getMesesPagados(); ?>"><br>
            Porcentaje: <input type="text" name="porcentaje" value="<?php echo $descuento->getPorcentaje(); ?>"><br>
            Plan: <select name="plan">
                <?php foreach($planes as $plan): ?>
                <?php if ($plan->getId() == $id_plan_asociado){ ?>
                    <option value="<?php echo $plan->getId(); ?>" selected><?php echo $plan->getNombre(); ?></opcion>
                <?php } else { ?>
                    <option value="<?php echo $plan->getId(); ?>"><?php echo $plan->getNombre(); ?></opcion>
                <?php } ?>
                  <?php endforeach; ?>
            </select>
          <br>
         
         <input type="submit" value="Modificar" name="editar">
            <input type="submit" value="Cancelar" name="editar">
         </form>
         </section>
        
        </div> <!-- /container -->
    </body>
</html>
