<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       
        <h1>Agregar user</h1>
        <form method="post">
          Nombre: <input type="text" name="nombre"><br>
          Apellido: <input type="text" name="apellido"><br>
          Email: <input type="text" name="email"><br>
          Contraseña: <input type="text" name="contrasenia"><br>
          <input type="submit" value="Agregar">
        </form>
    </body>
</html>
