<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        // put your code here
        ?>
        Bienvenido a cuenta/cuenta.phtml <?php echo $usuario1->getNombre(); ?> <?php echo $usuario1->getApellido(); ?>...
        <br><br>
  
        
    </body>
</html>
