<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <h1>Eliminar usuario</h1>
        Are you sure you want to delete user <?php echo $user->getNombre(); ?> <?php echo $user->getApellido(); ?>? <br/>
        <form method="post">
          <input type="submit" value="Eliminar">
        </form>
    </body>
</html>
