<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        
        <h1>Editar usuario</h1>
        <form method="post">
            Nombre: <input type="text" name="nombre" value="<?php echo $user->getNombre(); ?>"><br>
            Apellido: <input type="text" name="apellido" value="<?php echo $user->getApellido(); ?>"><br>
            Email: <input type="text" name="email" value="<?php echo $user->getEmail(); ?>"><br>
            Contraseña: <input type="text" name="contrasenia" value="<?php echo $user->getContrasenia(); ?>"><br>
          
          <input type="submit" value="Modificar">
        </form>
    </body>  
</html>
