<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>

    </head>
    <body>
       
        <div class="container">

            
            <section id="seccion">
                
                <?php
                 $title = 'Mi Cuenta';
                 $this->headTitle($title);
                 ?>
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
                 <br><br>

        
                 <form name="form1" method="post">
                     
                     <?php $tipo0 = 0; ?>
                     <?php $tipo1 = 1; ?>
                    <a href="<?php echo $this->url('login', array('action' => 'login'),
                            array('query' => array('tipousuario' => $tipo0),
                           )); ?>">Admin</a>
                   

           
                 <br><br><br>
               
                      <a href="<?php echo $this->url('login', array('action' => 'login'),
                            array('query' => array('tipousuario' => $tipo1),
                           )); ?>">Fotografo</a>
                 </form>
            
           </section>

        </div> <!-- /container -->
        
    </body>
</html>
