<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Mi Cuenta';
                 $this->headTitle($title);
                 ?>
                 <h1><?php echo $this->escapeHtml($title); ?></h1>
                 <p>
                     <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Agregar usuario</a>
                 </p>
        
                <?php if (isset($users)) : ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                    </tr>
                    </thead>
                <?php foreach($users as $user): ?>
                    <tbody>
                    <tr>
                        <td><?php echo $user->getNombre(); ?></td>
                        <td><?php echo $user->getApellido(); ?></td>
                        <td><?php echo $user->getEmail(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user->getId()));?>">Edit</a> |
                            <a href="<?php echo $this->url('user', array('action'=>'delete', 'id' => $user->getId()));?>">Delete</a>
                        </td>
                    </tr>
                    </tbody>
                <?php endforeach; ?>
                </table>
                <?php endif; ?>
            
           </section>

        </div> <!-- /container -->
        
    </body>
</html>
