<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
       
        <div class="container">
            
            <section id="seccion">
                
                <?php
                 $title = 'Mi Cuenta';
                 $this->headTitle($title);
                 ?>
                 <h1><?php echo $this->escapeHtml($title); ?></h1>

        
                <form method="post">
                    <input type="hidden" name="tipousuario" value="1">
                    Email: <input type="text" name="email" value=""><br>
                    Contraseña: <input type="text" name="contrasenia" value=""><br>

                    <input type="submit" value="Ingresar" name="ingresar">
                </form>
            
           </section>

        </div> <!-- /container -->
        
    </body>
</html>
